// PENDIENTE -> OK|ERROR -> (si OK, fase 3) EMITIDO|SIN_DOCUMENTO|ERROR_EMISION
export enum EstadoDetalleEmision {
  PENDIENTE = 'PENDIENTE',
  OK = 'OK',
  ERROR = 'ERROR',
  EMITIDO = 'EMITIDO',
  SIN_DOCUMENTO = 'SIN_DOCUMENTO',
  ERROR_EMISION = 'ERROR_EMISION',
}
