// CARGADO -> VALIDANDO -> VALIDADO_OK|VALIDADO_CON_ERRORES|ERROR_VALIDACION -> PROCESANDO_DOCUMENTOS (transitorio,
// fase 3) -> EMITIENDO -> EMITIDO|EMITIDO_CON_ERRORES|ERROR_EMISION
export enum EstadoLoteEmision {
  CARGADO = 'CARGADO',
  VALIDANDO = 'VALIDANDO',
  VALIDADO_OK = 'VALIDADO_OK',
  VALIDADO_CON_ERRORES = 'VALIDADO_CON_ERRORES',
  ERROR_VALIDACION = 'ERROR_VALIDACION',
  PROCESANDO_DOCUMENTOS = 'PROCESANDO_DOCUMENTOS',
  EMITIENDO = 'EMITIENDO',
  EMITIDO = 'EMITIDO',
  EMITIDO_CON_ERRORES = 'EMITIDO_CON_ERRORES',
  ERROR_EMISION = 'ERROR_EMISION',
  ELIMINADO = 'ELIMINADO',
}
