// PENDIENTE -> OK|ERROR (fase 2) -> (si OK, fase 4) FACTURADO|SIN_DOCUMENTO|ERROR_FACTURACION
export enum EstadoDetalleVidaSalud {
  PENDIENTE = 'PENDIENTE',
  OK = 'OK',
  ERROR = 'ERROR',
  FACTURADO = 'FACTURADO',
  SIN_DOCUMENTO = 'SIN_DOCUMENTO',
  ERROR_FACTURACION = 'ERROR_FACTURACION',
}
